### ISSUE TITLE
protocol field splitting breaks TRANSFER command parsing in some cases

### ISSUE THREAD

**Issue by joeyh** [Lykos153/git-annex-remote-gdrive#1]
The git-annex special remote protocol is somewhat unusual in that the last field of a line can contain whitespace, while all previous fields cannot. So, simply splitting by whitespace can result in more fields than expected, when there is in fact whitespace in the last field.

This is particularly a problem for TRANSFER, since the filename passed as its last field does contain whitespace in some edge cases. Note that the external special remote documentation used to incorrectly say it never contained whitespace.

Your code has this problem, and I've updated the template that it's based on to fix the problem. So see commit fdbfe8816810f1a8703d14868e28748ce844bd15 to git-annex for a way to fix this.

**Comment by Lykos153** [comment]
Fixed, thanks!
